name: Check and update

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */2 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4

      - name: Set Git user
        run: |
          git config --global user.email "dany.marques90@gmail.com"
          git config --global user.name "danymarques"

      - name: Run newVersion.sh
        run: ./newVersion.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
